// Generates out/amma-explainer.srt and VOICEOVER.md from src/script.ts so the
// subtitles, the voice-over script and the video always share one timeline.
//   npm run subs
import {mkdirSync, writeFileSync} from 'node:fs';
import {FPS, TIMED_SCENES, TOTAL_FRAMES} from '../src/script';

const MAX_LINE = 42;

const srtTime = (seconds: number) => {
  const ms = Math.round(seconds * 1000);
  const h = Math.floor(ms / 3_600_000);
  const m = Math.floor((ms % 3_600_000) / 60_000);
  const s = Math.floor((ms % 60_000) / 1000);
  const r = ms % 1000;
  const p = (n: number, w = 2) => String(n).padStart(w, '0');
  return `${p(h)}:${p(m)}:${p(s)},${p(r, 3)}`;
};

const clock = (seconds: number) => {
  const m = Math.floor(seconds / 60);
  const s = seconds - m * 60;
  return `${m}:${s.toFixed(1).padStart(4, '0')}`;
};

/** Splits a cue into at most two balanced lines of ≤ MAX_LINE characters where possible. */
const wrap = (text: string) => {
  if (text.length <= MAX_LINE) return text;
  const words = text.split(' ');
  let best = text;
  let bestScore = Infinity;
  for (let i = 1; i < words.length; i++) {
    const a = words.slice(0, i).join(' ');
    const b = words.slice(i).join(' ');
    const score = Math.max(a.length, b.length) + (a.length > MAX_LINE || b.length > MAX_LINE ? 100 : 0);
    if (score < bestScore) {
      bestScore = score;
      best = `${a}\n${b}`;
    }
  }
  return best;
};

// ---- SRT -------------------------------------------------------------------
const srt: string[] = [];
let n = 1;
for (const scene of TIMED_SCENES) {
  const offset = scene.from / FPS;
  for (const cue of scene.cues) {
    srt.push(`${n++}\n${srtTime(offset + cue.start)} --> ${srtTime(offset + cue.end)}\n${wrap(cue.text)}\n`);
  }
}
mkdirSync('out', {recursive: true});
writeFileSync('out/amma-explainer.srt', srt.join('\n'));

// ---- VOICEOVER.md ------------------------------------------------------------
const words = (s: string) => s.split(/\s+/).filter(Boolean).length;
const totalWords = TIMED_SCENES.reduce((sum, s) => sum + words(s.cues.map((c) => c.text).join(' ')), 0);
const totalSeconds = TOTAL_FRAMES / FPS;

const md: string[] = [];
md.push('# AMMA explainer: voice-over script');
md.push('');
md.push('<!-- Generated by `npm run subs` from src/script.ts. Edit the script there, not here. -->');
md.push('');
md.push(
  `Runtime **${clock(totalSeconds)}** (${TOTAL_FRAMES} frames at ${FPS} fps) · ${totalWords} words · about ${Math.round(
    (totalWords / totalSeconds) * 60,
  )} words per minute.`,
);
md.push('');
md.push('**Voice:** one narrator, warm and professional, international English. Leave the music bed (if any) low.');
md.push('Timecodes are absolute from the start of the video. Each line should start on its timecode and finish before the next.');
md.push('Every fact is from the AMMA 2026 partner brochure (EN print edition); page references are listed under each scene.');
md.push('');
md.push('**Pronunciation:** AMMA = "AM-ma" · ICMM = "I-C-M-M" · TSM = "T-S-M" · CMSI = "C-M-S-I" · CRIRSCO = "cris-co" ·');
md.push('Akhtala = "akh-ta-LA" · Alaverdi = "a-la-ver-DEE" · Kajaran = "ka-ja-RAN" · Agarak = "a-ga-RAK" · Tsaghkadzor = "tsakh-kad-ZOR" ·');
md.push('Eurometaux = "euro-meh-TOE" · armmining.am = "arm-mining dot A-M".');
md.push('');
md.push('| # | Scene | In | Out |');
md.push('|---|---|---|---|');
TIMED_SCENES.forEach((s, i) => {
  md.push(`| ${i + 1} | ${s.name} | ${clock(s.from / FPS)} | ${clock((s.from + s.durationInFrames) / FPS)} |`);
});
md.push('');

TIMED_SCENES.forEach((s, i) => {
  const start = s.from / FPS;
  md.push(`## ${i + 1}. ${s.name} (${clock(start)} to ${clock(start + s.duration)})`);
  md.push('');
  md.push(`*On screen:* ${s.visuals}`);
  md.push('');
  md.push(`*Delivery:* ${s.delivery}`);
  md.push('');
  md.push('| Time | Line |');
  md.push('|---|---|');
  for (const c of s.cues) {
    md.push(`| ${clock(start + c.start)} to ${clock(start + c.end)} | ${c.text} |`);
  }
  md.push('');
  md.push(`*Sources:* ${s.sources.join('; ')}`);
  md.push('');
});

md.push('## Full read-through');
md.push('');
for (const s of TIMED_SCENES) {
  md.push(s.cues.map((c) => c.text).join(' '));
  md.push('');
}
writeFileSync('VOICEOVER.md', md.join('\n').replace(/\n{3,}/g, '\n\n'));

console.log(`Wrote out/amma-explainer.srt (${n - 1} cues) and VOICEOVER.md (${totalWords} words, ${clock(totalSeconds)})`);
